### ISSUE TITLE
Bottom of MacLibrary sits below the top of the dock

### ISSUE THREAD

**Issue by adude007** [themaclibrary/themaclibrary.github.io#1]
<img width="363" alt="Screenshot 2023-03-20 at 10 09 33 AM" src="https://user-images.githubusercontent.com/73857010/226365617-6e7fa52c-344b-45a4-b3ad-42aaa18f50c8.png">

Image shows MacLibrary below top of dock. Cannot sort bottom app in list. Cannot see name of app in list row when selecting app to open.

**Comment by adude007** [comment]
Main page download link is to V1.0.1, no issue with v3

**Comment by ThaliaMyers** [comment]
> Main page download link is to V1.0.1, no issue with v3

Sorry about that. I’ve updated the main link now. Hope everything works ok now.
